sudo: required

services:
  - docker

before_script:
  - docker build -t maxmilton/net-tools .

script:
  - docker run -v $(pwd):/project --rm maxmilton/net-tools --version

# TODO: Automatically trigger a new image on Docker hub or revoke image if failed
